name: flutter_floating
description: Flutter privileges free suspension window, support global, single page suspension, support edge adsorption position saving, up and down sliding area control and screen rotation window after the position repair and so on.

version: 1.0.9
homepage: https://github.com/LvKang-insist/Floating

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  test: ^1.17.10
flutter:

  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.lvkang.floating
    iosBundleIdentifier: com.lvkang.floating
